Feat navbar and authentication
SyedSibtainRazvi/receptor-app pull request #1
Opened 2024-07-11 08:37 UTC by SyedSibtainRazvi

Implemented Navbar
Implemented Signup, SignIn, SignOut and Session

2024-07-12 06:19 UTC, SujayPrabhu96 requested changes

2024-07-12 06:19 UTC, SujayPrabhu96 commented on app/controllers/sessions_controller.rb
> +  end
Leave a empty line after this

2024-07-12 06:19 UTC, SujayPrabhu96 commented on app/controllers/users_controller.rb
> +          redirect_to '/'
```suggestion
          redirect_to root_path
```

2024-07-12 06:19 UTC, SujayPrabhu96 commented on app/controllers/users_controller.rb
> +          redirect_to '/'
Fix the indentation in this file

2024-07-12 06:19 UTC, SujayPrabhu96 commented on app/helpers/application_helper.rb
> +        User.find(session[:user_id]) if session[:user_id]
If the User is not present, it will raise an exception. We need to handle the exception

2024-07-12 06:19 UTC, SujayPrabhu96 commented on app/models/user.rb
> +                  format: { with: /\S+@\S+/ },
We can set this regex expression for validation
https://stackoverflow.com/a/66588324

2024-07-12 06:19 UTC, SujayPrabhu96 commented on app/views/users/_form.html.erb
> +    <% flash.now[:alert] = "Validation error: " + @user.errors.full_messages.join(", ") %>
Here we are setting the flash message, but not rendering it. Any specific reason for this?

2024-07-12 06:19 UTC, SujayPrabhu96 commented on db/migrate/20240711082010_create_users.rb
> +      t.string :email
We have uniqueness validation on `email` in model. We need to have that at DB level as well

2024-07-12 06:20 UTC, SujayPrabhu96 commented
@SyedSibtainRazvi Please fix the indentation

2024-07-12 06:21 UTC, SujayPrabhu96 commented on app/controllers/sessions_controller.rb
> +  end
Leave an empty line after each action

2024-07-12 09:36 UTC, SyedSibtainRazvi commented on app/controllers/sessions_controller.rb
> +  end
Done

2024-07-12 09:44 UTC, SyedSibtainRazvi commented on app/controllers/users_controller.rb
> +          redirect_to '/'
Done

2024-07-12 09:48 UTC, SyedSibtainRazvi commented on app/models/user.rb
> +                  format: { with: /\S+@\S+/ },
Done

2024-07-12 09:50 UTC, SyedSibtainRazvi commented on app/views/users/_form.html.erb
> +    <% flash.now[:alert] = "Validation error: " + @user.errors.full_messages.join(", ") %>
We are rendering it in the application.html.erb

2024-07-12 09:51 UTC, SyedSibtainRazvi commented on db/migrate/20240711082010_create_users.rb
> +      t.string :email
Did not get it

2024-07-12 09:51 UTC, SyedSibtainRazvi commented on app/controllers/sessions_controller.rb
> +  end
Sure

2024-07-12 11:27 UTC, SyedSibtainRazvi commented on app/helpers/application_helper.rb
> +        User.find(session[:user_id]) if session[:user_id]
Done

2024-07-12 11:31 UTC, SyedSibtainRazvi commented on db/migrate/20240711082010_create_users.rb
> +      t.string :email
Done

2024-07-15 03:58 UTC, SujayPrabhu96 approved these changes

2024-07-15 04:00 UTC, merged